name: Linux_Container_Workflow

on: [workflow_dispatch]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Create env file'
          run: |
            echo "${{ secrets.ENV_FILE }}" > .env

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sketch-ai:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sketch-ai:${{ github.sha }}

        - name: 'Deploy to Azure Container App'
          uses: azure/container-apps-deploy-action@v1
          with:
            acrName: sketchai
            containerAppName: container-app-sketch-ai
            resourceGroup: ContainerApp-Sketch-AI
            imageToDeploy: sketchai.azurecr.io/sketch-ai:${{ github.sha }}
